# Generated by Django 5.0 on 2025-10-17 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieRegionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_stats', to='movies.movie')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_stats', to='movies.region')),
            ],
            options={
                'indexes': [models.Index(fields=['movie', 'region'], name='movies_movi_movie_i_51c503_idx')],
                'unique_together': {('movie', 'region')},
            },
        ),
    ]
